function onCreate()
    precacheImage("mindLyrics")
    precacheImage("ogLyrics")
end

function onCreatePost()
    -- lmao animated lyrics moment, a LOT of animations incoming, hopefully this wont be ass for performance (begs, it shouldn't be, the spritesheet is under 1000x1000 so should be ok)
    makeAnimatedLuaSprite("mindLyrics", "mindLyrics", 0, 0)
    addAnimationByPrefix('mindLyrics', 'IM', '1im', 1, false)
    addAnimationByPrefix('mindLyrics', 'AL', '2al', 1, false)
    addAnimationByPrefix('mindLyrics', 'ALREADY', '3already', 1, false)
    addAnimationByPrefix('mindLyrics', 'IN', '4in', 1, false)
    addAnimationByPrefix('mindLyrics', 'YOUR', '5your', 1, false)
    addAnimationByPrefix('mindLyrics', 'MIND', '6mind', 1, false)
    addAnimationByPrefix('mindLyrics', 'TO', '7to', 1, false)
    addAnimationByPrefix('mindLyrics', 'TOGE', '8toge', 1, false)
    addAnimationByPrefix('mindLyrics', 'TOGETHER', '9together', 1, false)
    addAnimationByPrefix('mindLyrics', 'WERE', '10were', 1, false)
    addAnimationByPrefix('mindLyrics', 'GON', '11gon', 1, false)
    addAnimationByPrefix('mindLyrics', 'GONNA', '12gonna', 1, false)
    addAnimationByPrefix('mindLyrics', 'DIE', '13die', 1, false)
    addAnimationByPrefix('mindLyrics', 'WHEN', '14when', 1, false)
    addAnimationByPrefix('mindLyrics', 'WE', '15we', 1, false)
    addAnimationByPrefix('mindLyrics', 'SEEK', '16seek', 1, false)
    addAnimationByPrefix('mindLyrics', 'WE-2', '17we', 1, false)
    addAnimationByPrefix('mindLyrics', 'AL-2', '18al', 1, false)
    addAnimationByPrefix('mindLyrics', 'ALWAYS', '19always', 1, false)
    addAnimationByPrefix('mindLyrics', 'FIND', '20find', 1, false)
    addAnimationByPrefix('mindLyrics', 'NO', '21no', 1, false)
    addAnimationByPrefix('mindLyrics', 'MAT', '22mat', 1, false)
    addAnimationByPrefix('mindLyrics', 'MATTER', '23matter', 1, false)
    addAnimationByPrefix('mindLyrics', 'IF', '24if', 1, false)
    addAnimationByPrefix('mindLyrics', 'WE-3', '25we', 1, false)
    addAnimationByPrefix('mindLyrics', 'WASTE', '26waste', 1, false)
    addAnimationByPrefix('mindLyrics', 'SOME', '27some', 1, false)
    addAnimationByPrefix('mindLyrics', 'TRIES', '28tries', 1, false)

    addAnimationByPrefix('mindLyrics', 'WHEN-2', '29when', 1, false)
    addAnimationByPrefix('mindLyrics', 'WE-4', '30we', 1, false)
    addAnimationByPrefix('mindLyrics', 'SEEK-2', '31seek', 1, false)
    addAnimationByPrefix('mindLyrics', 'WE-5', '32we', 1, false)
    addAnimationByPrefix('mindLyrics', 'AL-3', '33al', 1, false)
    addAnimationByPrefix('mindLyrics', 'ALWAYS-2', '34always', 1, false)
    addAnimationByPrefix('mindLyrics', 'FIND-2', '35find', 1, false)
    addAnimationByPrefix('mindLyrics', 'NO-2', '36no', 1, false)
    addAnimationByPrefix('mindLyrics', 'MAT-2', '37mat', 1, false)
    addAnimationByPrefix('mindLyrics', 'MATTER-2', '38matter', 1, false)
    addAnimationByPrefix('mindLyrics', 'IF-2', '39if', 1, false)
    addAnimationByPrefix('mindLyrics', 'WE-6', '40we', 1, false)
    addAnimationByPrefix('mindLyrics', 'WASTE-2', '41waste', 1, false)
    addAnimationByPrefix('mindLyrics', 'SOME-2', '42some', 1, false)
    addAnimationByPrefix('mindLyrics', 'TRIES-2', '43tries', 1, false)

    playAnim("mindLyrics", "IM", true, false, 0)
    setProperty('mindLyrics.antialiasing', false)
    addLuaSprite('mindLyrics', false)
    scaleObject("mindLyrics", 3.0, 3.0)
    setObjectCamera("mindLyrics", 'hud')
    setProperty("mindLyrics.visible", false)

    --ok this one is larger, pls dont lag ty

    makeAnimatedLuaSprite("ogLyrics", "ogLyrics", 0, 0)
    addAnimationByPrefix('ogLyrics', 'LET', '1let', 1, false)
    addAnimationByPrefix('ogLyrics', 'YOUR', '2your', 1, false)
    addAnimationByPrefix('ogLyrics', 'SPI', '3spi', 1, false)
    addAnimationByPrefix('ogLyrics', 'SPIRIT', '4spirit', 1, false)
    addAnimationByPrefix('ogLyrics', 'LEAVE', '5leave', 1, false)
    addAnimationByPrefix('ogLyrics', 'YOUR-2', '6your', 1, false)
    addAnimationByPrefix('ogLyrics', 'BO', '7bo', 1, false)
    addAnimationByPrefix('ogLyrics', 'BODY', '8body', 1, false)
    addAnimationByPrefix('ogLyrics', 'I', '9i', 1, false)
    addAnimationByPrefix('ogLyrics', 'AM', '10am', 1, false)
    addAnimationByPrefix('ogLyrics', 'GOD', '11god', 1, false)
    addAnimationByPrefix('ogLyrics', 'AND', '12and', 1, false)
    addAnimationByPrefix('ogLyrics', 'YOURE', '13youre', 1, false)
    addAnimationByPrefix('ogLyrics', 'NO', '14no', 1, false)
    addAnimationByPrefix('ogLyrics', 'NOBO', '15nobo', 1, false)
    addAnimationByPrefix('ogLyrics', 'NOBODY', '16nobody', 1, false)
    addAnimationByPrefix('ogLyrics', 'I-2', '17i', 1, false)
    addAnimationByPrefix('ogLyrics', 'WILL', '18will', 1, false)
    addAnimationByPrefix('ogLyrics', 'TAKE', '19take', 1, false)
    addAnimationByPrefix('ogLyrics', 'YOU', '20you', 1, false)
    addAnimationByPrefix('ogLyrics', 'TO', '21to', 1, false)
    addAnimationByPrefix('ogLyrics', 'MY', '22my', 1, false)
    addAnimationByPrefix('ogLyrics', 'WORLD', '23world', 1, false)
    addAnimationByPrefix('ogLyrics', 'THEN', '24then', 1, false)
    addAnimationByPrefix('ogLyrics', 'ILL', '25ill', 1, false)
    addAnimationByPrefix('ogLyrics', 'LEAVE-2', '26leave', 1, false)
    addAnimationByPrefix('ogLyrics', 'YOU-2', '27you', 1, false)
    addAnimationByPrefix('ogLyrics', 'WITH', '28with', 1, false)
    addAnimationByPrefix('ogLyrics', 'WITHOUT', '29out', 1, false)
    addAnimationByPrefix('ogLyrics', 'WORD', '30word', 1, false)
    addAnimationByPrefix('ogLyrics', 'HIDE', '31hide', 1, false)
    addAnimationByPrefix('ogLyrics', 'AND-2', '32and', 1, false)
    addAnimationByPrefix('ogLyrics', 'SEEK', '33seek', 1, false)
    addAnimationByPrefix('ogLyrics', 'CANT', '34cant', 1, false)
    addAnimationByPrefix('ogLyrics', 'YOU-3', '35you', 1, false)
    addAnimationByPrefix('ogLyrics', 'SEE', '36see', 1, false)
    addAnimationByPrefix('ogLyrics', 'YOURE-2', '37youre', 1, false)
    addAnimationByPrefix('ogLyrics', 'THE', '38the', 1, false)
    addAnimationByPrefix('ogLyrics', 'ONE', '39one', 1, false)
    addAnimationByPrefix('ogLyrics', 'IM', '40im', 1, false)
    addAnimationByPrefix('ogLyrics', 'LOOK', '41look', 1, false)
    addAnimationByPrefix('ogLyrics', 'LOOKING', '42looking', 1, false)
    addAnimationByPrefix('ogLyrics', 'FOR', '43for', 1, false)
    addAnimationByPrefix('ogLyrics', 'THROUGH', '44through', 1, false)
    addAnimationByPrefix('ogLyrics', 'THE-2', '45the', 1, false)
    addAnimationByPrefix('ogLyrics', 'SCREEN', '46screen', 1, false)
    addAnimationByPrefix('ogLyrics', 'I-3', '47i', 1, false)
    addAnimationByPrefix('ogLyrics', 'CAN', '48can', 1, false)
    addAnimationByPrefix('ogLyrics', 'SEE-2', '49see', 1, false)
    addAnimationByPrefix('ogLyrics', 'MORE', '50more', 1, false)
    playAnim("ogLyrics", "LET", true, false, 0)
    setProperty('ogLyrics.antialiasing', false)
    addLuaSprite('ogLyrics', false)
    scaleObject("ogLyrics", 3.0, 3.0)
    setObjectCamera("ogLyrics", 'hud')
    setProperty("ogLyrics.visible", false)
end

function onEvent(name, value1, value2)
    if name == 'imageLyrics' then        
        if value1 == '' then
            setProperty("mindLyrics.visible", false)
        else
            setProperty("mindLyrics.visible", true)
            playAnim("mindLyrics", string.upper(value1), true, false, 0)
        end

        if value2 == '' then
            setProperty("ogLyrics.visible", false)
        else
            setProperty("ogLyrics.visible", true)
            playAnim("ogLyrics", string.upper(value2), true, false, 0)
        end
    end
end