function onCreate()
    precacheImage("trinityLegacyLyrics")
end

function onCreatePost()
    -- BEHOLD, THE LARGEST AMOUNT OF ANIMATION PREFIXES YOU'RE EVER FUCKING SEEN!!!!!
    -- sorry. -snow
    makeAnimatedLuaSprite("trinityLegacyLyrics", "trinityLegacyLyrics", 287, 75)
    addAnimationByPrefix('trinityLegacyLyrics', 'LET', '1let', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOUR', '2your', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SPI', '3spii', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SPIRIT', '3spirit', 1, false) -- i fucked up the count early and im not renaming all of these stfu >:(
    addAnimationByPrefix('trinityLegacyLyrics', 'LEAVE', '4leave', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOUR-2', '5your', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'BO', '6bo', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'BODY', '7body', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'I', '8i', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'AM', '9am', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'GOD', '10god', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'AND', '11and', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOURE', '12youre', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'NO', '13no', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'NOBO', '14nobo', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'NOBODY', '15nobody', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'I-2', '16i', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'WILL', '17will', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'TAKE', '18take', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOU', '19you', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'TO', '20to', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'MY', '21my', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'WORLD', '22world', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'THEN', '23then', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'ILL', '24ill', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'LEAVE-2', '25leave', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOU-2', '26you', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'WITH', '27with', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'WITHOUT', '28without', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'WORD', '28word', 1, false) -- fucked it here too haha
    addAnimationByPrefix('trinityLegacyLyrics', 'HIDE', '29hide', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'AND-2', '30and', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SEEK', '31seek', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'CANT', '32cant', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOU-3', '33you', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SEE', '34see', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'BOY', '35boy', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'BOYFRIEND', '36boyfriend', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'IS', '37is', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'NO-2', '38no', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'NOTHING', '39nothing', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'FOR', '40for', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'ME', '41me', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOURE-2', '42youre', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'THE', '43the', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'ONE', '44one', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'IM', '45im', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'LOOK', '46look', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'LOOKING', '47looking', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'FOR-2', '48for', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'THROUGH', '49through', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'THE-2', '50the', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SCREEN', '51screen', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'I-3', '52i', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'CAN', '53can', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SEE-2', '54see', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'MORE', '55more', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'PLAY', '56play', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'THE-3', '57the', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'NOTES', '58notes', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'ITS', '59its', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SO', '60so', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'FUN', '61fun', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SO-2', '62so', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SONIC', '63sonic', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'LOVES', '64loves', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'TO-2', '65to', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'SEE-3', '66see', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOU-4', '67you', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'RUN', '68run', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'FROM', '69from', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'A', '70a', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'FATE', '71fate', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOU-5', '72you', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'WONT', '73wont', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'ES', '74es', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'ESCAPE', '75escape', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'WHEN', '76when', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'YOU-6', '77you', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'DIE', '78die', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'WE', '79we', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'MEET', '80meet', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'AG', '81ag', 1, false)
    addAnimationByPrefix('trinityLegacyLyrics', 'AGAIN', '82again', 1, false)
    playAnim("trinityLegacyLyrics", "LET", true, false, 0)
    setProperty('trinityLegacyLyrics.antialiasing', false)
    addLuaSprite('trinityLegacyLyrics', false)
    scaleObject("trinityLegacyLyrics", 1.75, 1.75)
    setObjectCamera("trinityLegacyLyrics", 'hud')
    setProperty("trinityLegacyLyrics.alpha", 0.0001)

    if downscroll then
        setProperty("trinityLegacyLyrics.y", 0)
    end
end

function onEvent(name, value1, value2)
    if name == 'trinityLegacyLyrics' then
        if value1 == '' then
            setProperty("trinityLegacyLyrics.alpha", 0.0001)
        else
            setProperty("trinityLegacyLyrics.alpha", 1)
            playAnim("trinityLegacyLyrics", string.upper(value1), true, false, 0)
        end
    end
end